### ISSUE TITLE
pip can't install

### ISSUE THREAD

**Issue by icarito** [Zulko/pompei#1]
$ sudo pip install ez_setup pompei
Collecting ez-setup
  Downloading ez_setup-0.9.tar.gz
Collecting pompei
  Downloading pompei-0.1.03.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_vzzzwm_/pompei/setup.py", line 20, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

```
  File "<string>", line 20, in <module>

  File "/tmp/pip-build-_vzzzwm_/pompei/setup.py", line 20, in <module>

    long_description=open('README.rst').read(),

FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_vzzzwm_/pompei
```

**Comment by Zulko** [comment]
Thanks for the report. I fixed it, it should work now.
